# Generated by Django 5.2.3 on 2025-08-18 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_application_status_alter_application_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('qualification_file', models.FileField(blank=True, null=True, upload_to='qualifications/')),
                ('id_file', models.FileField(blank=True, null=True, upload_to='ids/')),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='cvs/')),
                ('student_number', models.CharField(blank=True, max_length=20)),
                ('enrolled_courses', models.ManyToManyField(related_name='students', to='core.course')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course')),
            ],
        ),
    ]
