# Generated by Django 5.2.3 on 2025-08-18 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='id_number',
            field=models.CharField(default=1234567890987, max_length=13),
            preserve_default=False,
        ),
    ]
