# Generated by Django 5.2.3 on 2025-08-18 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_application_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='id_number',
            field=models.CharField(default=1234567890098, max_length=13),
            preserve_default=False,
        ),
    ]
