# Generated by Django 5.2.5 on 2025-08-23 15:12

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_student_id_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_number',
        ),
        migrations.AlterField(
            model_name='application',
            name='cv',
            field=models.FileField(storage=storages.backends.s3.S3Storage(), upload_to='cvs/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='id_doc',
            field=models.FileField(storage=storages.backends.s3.S3Storage(), upload_to='ids/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='qualification_doc',
            field=models.FileField(storage=storages.backends.s3.S3Storage(), upload_to='qualifications/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='cv_file',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='cvs/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id_file',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='ids/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='qualification_file',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='qualifications/'),
        ),
    ]
