# Generated by Django 5.2.5 on 2025-08-23 17:50

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_student_student_number_alter_application_cv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='cv',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='cvs/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='highest_qualification',
            field=models.CharField(blank=True, choices=[('Grade 11', 'Grade 11'), ('Grade 12', 'Grade 12'), ('Certificate', 'Certificate'), ('Diploma', 'Diploma'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='motivation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='qualification_doc',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='qualifications/'),
        ),
    ]
