# Generated by Django 5.2.5 on 2025-08-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_application_cv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='enrollment_month',
            field=models.CharField(default='September 2025', max_length=20),
        ),
    ]
