# Generated by Django 5.2.5 on 2025-08-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_application_enrollment_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_date',
            field=models.DateField(auto_now_add=True, default='2025-08-23'),
            preserve_default=False,
        ),
    ]
