# Generated by Django 5.2.5 on 2025-08-23 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_application_application_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='enrollment_month',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
