# Generated by Django 5.2.3 on 2025-08-18 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='status',
        ),
        migrations.AlterField(
            model_name='application',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course'),
        ),
        migrations.AlterField(
            model_name='application',
            name='cv',
            field=models.FileField(upload_to='cvs/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='highest_qualification',
            field=models.CharField(choices=[('Grade 11', 'Grade 11'), ('Grade 12', 'Grade 12'), ('Certificate', 'Certificate'), ('Diploma', 'Diploma'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='id_doc',
            field=models.FileField(upload_to='ids/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='qualification_doc',
            field=models.FileField(upload_to='qualifications/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
