# Generated by Django 5.2.5 on 2025-08-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_applied_on_application_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='reference_number',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
