# Generated by Django 5.2.5 on 2025-08-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_application_reference_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('enrolled', 'Enrolled'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
