# Generated by Django 5.2.5 on 2025-08-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='cvs/'),
        ),
        migrations.AddField(
            model_name='student',
            name='id_file',
            field=models.FileField(blank=True, null=True, upload_to='ids/'),
        ),
        migrations.AddField(
            model_name='student',
            name='qualification_file',
            field=models.FileField(blank=True, null=True, upload_to='qualifications/'),
        ),
    ]
